### PR TITLE
Fix intersects for multipolygons.

### PR DESCRIPTION
**Pull request by rgwozdz**
Fixes faulty intersection result with certain geometry arguments.  See https://github.com/terraformer-js/terraformer/issues/84 for details.

### CODE REVIEW

**Comment by rgwozdz** [comment]
build failure doesn't seem related to the PR changes.

**Comment by jgravois** [comment]
very cool old friend. 🙏 

> build failure doesn't seem related to the PR changes.

indubitably. i'll find time to track down a fix in the next couple days so i can give your PR a proper review.

**Comment by jgravois** [comment]
this one _should be_ unblocked by #87

**Comment by rgwozdz** [comment]
Woot, the rebase of main fixed CI.

**Review by jgravois — APPROVED** [review]

**Pull request merged**
